// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/kv/v1/kv.proto

package kvv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_kv_v1_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_v1_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_v1_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// A client must resolve the previous write before increasing its sequence.
type MutationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value          string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ClientId       string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Expected       string                 `protobuf:"bytes,5,opt,name=expected,proto3" json:"expected,omitempty"`
	ExpectedExists bool                   `protobuf:"varint,6,opt,name=expected_exists,json=expectedExists,proto3" json:"expected_exists,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutationRequest) Reset() {
	*x = MutationRequest{}
	mi := &file_api_kv_v1_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationRequest) ProtoMessage() {}

func (x *MutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_v1_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationRequest.ProtoReflect.Descriptor instead.
func (*MutationRequest) Descriptor() ([]byte, []int) {
	return file_api_kv_v1_kv_proto_rawDescGZIP(), []int{1}
}

func (x *MutationRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MutationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MutationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MutationRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *MutationRequest) GetExpected() string {
	if x != nil {
		return x.Expected
	}
	return ""
}

func (x *MutationRequest) GetExpectedExists() bool {
	if x != nil {
		return x.ExpectedExists
	}
	return false
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Applied       bool                   `protobuf:"varint,3,opt,name=applied,proto3" json:"applied,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_kv_v1_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_kv_v1_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_kv_v1_kv_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Result) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *Result) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_kv_v1_kv_proto protoreflect.FileDescriptor

const file_api_kv_v1_kv_proto_rawDesc = "" +
	"\n" +
	"\x12api/kv/v1/kv.proto\x12\fraftgo.kv.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xb7\x01\n" +
	"\x0fMutationRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12\x1a\n" +
	"\bexpected\x18\x05 \x01(\tR\bexpected\x12'\n" +
	"\x0fexpected_exists\x18\x06 \x01(\bR\x0eexpectedExists\"f\n" +
	"\x06Result\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x18\n" +
	"\aapplied\x18\x03 \x01(\bR\aapplied\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x84\x02\n" +
	"\tKVService\x125\n" +
	"\x03Get\x12\x18.raftgo.kv.v1.GetRequest\x1a\x14.raftgo.kv.v1.Result\x12:\n" +
	"\x03Put\x12\x1d.raftgo.kv.v1.MutationRequest\x1a\x14.raftgo.kv.v1.Result\x12=\n" +
	"\x06Delete\x12\x1d.raftgo.kv.v1.MutationRequest\x1a\x14.raftgo.kv.v1.Result\x12E\n" +
	"\x0eCompareAndSwap\x12\x1d.raftgo.kv.v1.MutationRequest\x1a\x14.raftgo.kv.v1.ResultB\x17Z\x15go_prj/api/kv/v1;kvv1b\x06proto3"

var (
	file_api_kv_v1_kv_proto_rawDescOnce sync.Once
	file_api_kv_v1_kv_proto_rawDescData []byte
)

func file_api_kv_v1_kv_proto_rawDescGZIP() []byte {
	file_api_kv_v1_kv_proto_rawDescOnce.Do(func() {
		file_api_kv_v1_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kv_v1_kv_proto_rawDesc), len(file_api_kv_v1_kv_proto_rawDesc)))
	})
	return file_api_kv_v1_kv_proto_rawDescData
}

var file_api_kv_v1_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_kv_v1_kv_proto_goTypes = []any{
	(*GetRequest)(nil),      // 0: raftgo.kv.v1.GetRequest
	(*MutationRequest)(nil), // 1: raftgo.kv.v1.MutationRequest
	(*Result)(nil),          // 2: raftgo.kv.v1.Result
}
var file_api_kv_v1_kv_proto_depIdxs = []int32{
	0, // 0: raftgo.kv.v1.KVService.Get:input_type -> raftgo.kv.v1.GetRequest
	1, // 1: raftgo.kv.v1.KVService.Put:input_type -> raftgo.kv.v1.MutationRequest
	1, // 2: raftgo.kv.v1.KVService.Delete:input_type -> raftgo.kv.v1.MutationRequest
	1, // 3: raftgo.kv.v1.KVService.CompareAndSwap:input_type -> raftgo.kv.v1.MutationRequest
	2, // 4: raftgo.kv.v1.KVService.Get:output_type -> raftgo.kv.v1.Result
	2, // 5: raftgo.kv.v1.KVService.Put:output_type -> raftgo.kv.v1.Result
	2, // 6: raftgo.kv.v1.KVService.Delete:output_type -> raftgo.kv.v1.Result
	2, // 7: raftgo.kv.v1.KVService.CompareAndSwap:output_type -> raftgo.kv.v1.Result
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_kv_v1_kv_proto_init() }
func file_api_kv_v1_kv_proto_init() {
	if File_api_kv_v1_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kv_v1_kv_proto_rawDesc), len(file_api_kv_v1_kv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kv_v1_kv_proto_goTypes,
		DependencyIndexes: file_api_kv_v1_kv_proto_depIdxs,
		MessageInfos:      file_api_kv_v1_kv_proto_msgTypes,
	}.Build()
	File_api_kv_v1_kv_proto = out.File
	file_api_kv_v1_kv_proto_goTypes = nil
	file_api_kv_v1_kv_proto_depIdxs = nil
}
